---
name: Preview changes to GitHub configuration on Pull Request

on:
  pull_request:
    paths:
      - 'github-sync/github-data/*.yaml'

env:
 GITHUB_TOKEN: ${{ secrets.PULUMI_GITHUB_TOKEN }}
 PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
 GITHUB_OWNER: sigstore

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./check-yaml-sort.sh
        working-directory: ./github-sync
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - run: go mod download
      - uses: pulumi/actions@v3
        with:
          command: preview
          # stack-name: dev
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}